emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [0.000000, 1.000000, 0.000000]
    emissionVectorInverted: true
    name: "fireworks"
    radius: 0.200000
    shortEffect: false
    size: [1.000000, 1.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 0]
    blending: 1
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 0.500000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 30.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "butterfly"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [2.000000, 2.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.098876, [0.970803, 0.970803]]
    sizeVariation: [0.200000, 0.200000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/1AP/butterfly"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityVariation: 2.000000
layer1:
    activeLODS: [1, 1, 1, 0]
    alphaOverLife: [0.000000, 1.000000, 0.792185, 1.000000, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [179.000000, 153.000000, 47.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "leaf1"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [2.000000, 2.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.100000, 0.050000]
    sizeVariation: [0.100000, 0.100000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/alpha/leaf"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityVariation: 1.000000
layer2:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 1.000000, 0.792185, 1.000000, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [209.000000, 169.000000, 23.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "leaf2"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [2.000000, 2.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.100000, 0.050000]
    sizeVariation: [0.100000, 0.100000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/alpha/leaf_one"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityVariation: 1.000000
layer3:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 1.000000, 0.792185, 1.000000, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [150.000000, 150.000000, 74.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "leaf3"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [2.000000, 2.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.100000, 0.050000]
    sizeVariation: [0.100000, 0.100000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/alpha/leaf"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityVariation: 1.000000
layer4:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    blending: 1
    colorRandom: [0.000000, [209.000000, 169.000000, 23.000000, 255.000000], 0.558333, [150.000000, 150.000000, 74.000000, 255.000000], 0.989583, [179.000000, 153.000000, 47.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.100000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: true
    layerType: "particles"
    life: 0.150000
    lifeVariation: 0.100000
    loopEndTime: 0.500000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "leaf4"
    number: 500.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.150000, 0.150000]
    sprite: "../../../../Gfx/Particles/alpha/leaf_two"
    startTime: 0.000000
    type: "layer"
    velocity: 12.000000
