emitter:
    emissionAngle: 0.000000
    emissionRange: 20.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "smoke_sparks"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: 0.300000
    angle: 1.000000
    angleVariation: 360.000000
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.300000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "bubbles1"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [2.000000, 2.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.100000, 0.100000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.098876, [0.970803, 0.970803]]
    sizeVariation: [0.100000, 0.100000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/1AP/bubbles"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityVariation: 2.000000
