emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [0.000000, 0.000000, 0.500000]
    emissionVectorInverted: true
    name: "debris1"
    radius: 0.500000
    shortEffect: false
    size: [1.000000, 1.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [139.307388, 133.105057, 77.272369, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 16.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_rock"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.200000, 0.100000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/brick_anim_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 2.000000
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [133.404663, 117.159531, 70.762642, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_rock2"
    number: 40.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.050000, 0.050000]
    sizeVariation: [0.050000, 0.050000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/brick_anim_two"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 3.000000
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorRandom: [144.000000, 129.373535, 107.435799, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 15.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood"
    number: 15.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.050000, 0.495000]
    sizeVariation: [0.050000, 0.050000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 2.000000
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorRandom: [145.000000, 124.000000, 108.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 26.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood2"
    number: 15.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.025000, 0.250000]
    sizeVariation: [0.050000, 0.050000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 3.000000
