emitter:
    emissionAngle: 90.000000
    emissionRange: 60.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    radius: 0.500000
    shortEffect: false
    size: [0.000000, 1.200000, 0.000000]
    type: "oncircle"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.030200, 0.127300, 0.365300, 0.636600, 0.862800, 0.864700, 0.427000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [0.000000, [238.000000, 138.000000, 82.000000, 255.000000], 0.995900, [209.572006, 105.871597, 65.789902, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, 0.739900]
    forceCount: 1
    forceOverLife0: [0.000000, 0.993300, 0.461300, 0.366700, 1.000000, 0.434200, 2.080000, 1.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.462000
    lifeVariation: 0.441300
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.000000, 2.000000]
    sizeVariation: [0.150000, 0.150000]
    spin: 30.000000
    sprite: "../../Gfx/Particles/alpha/o2SMOKEB"
    startTime: 0.000000
    type: "layer"
    velocity: 0.343600
