emitter:
    emissionAngle: 60.000000
    emissionRange: 50.000000
    emissionVector: [0.100000, -0.010000, 2.000000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.050000, 0.500000, 0.990000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [0.000000, [248.844406, 217.638107, 162.283997, 255.000000], 0.987900, [255.000000, 226.062302, 178.498001, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, [0.000000, 0.000000, -2.000000], 0.300000, [0.010000, 0.000000, 0.000000], 0.900000, [0.000000, 0.000000, -0.938700]]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 3.000000
    loopEndTime: 6.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.250000]
    sizeOverLifeXY: [0.000000, [3.445100, 3.445100], 0.355700, [3.504900, 3.504900], 0.900000, [4.240400, 4.240400]]
    sizeVariation: [1.000000, 1.000000]
    spin: [0.000000, 5.000000, 0.300000, 0.000000]
    spinOverLife: [0.000000, 1.000000, 0.300000, 0.000000]
    sprite: "../../Gfx/Particles/alpha/o2SMOKEB"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 4.670200, 0.052500, 0.587800, 0.420000, 0.100000, 0.900000, 0.000000]
    velocityVariation: 1.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.030000, 0.500000, 0.990000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [0.000000, [255.000000, 235.696503, 186.614807, 255.000000], 0.987900, [255.000000, 225.910507, 187.451401, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, [0.000000, 0.000000, -0.366400], 0.330000, [0.010000, 0.010000, 0.358500], 0.900000, [0.000000, 0.000000, -0.340600]]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 2.000000
    loopEndTime: 6.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer"
    number: 25.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.250000]
    sizeOverLifeXY: [0.000000, [3.000000, 3.000000], 0.900000, [2.000000, 2.000000]]
    sizeVariation: [1.000000, 1.000000]
    sprite: "../../Gfx/Particles/alpha/o2SMOKEB"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 0.215000, 0.179000, 0.178100, 0.420000, 0.000000, 0.900000, 0.000000]
    velocityVariation: 1.000000
layer2:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.030000, 0.500000, 0.990000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 3
    colorOverLife: [0.000000, [255.000000, 196.000000, 47.000000, 255.000000], 0.558300, [255.000000, 225.910507, 187.451401, 255.000000], 0.682000, [140.688705, 1.120600, 24.136200, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, [0.000000, 0.000000, -0.366400], 0.330000, [0.010000, 0.010000, 0.358500], 0.900000, [0.000000, 0.000000, -0.340600]]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    loopEndTime: 6.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer"
    number: 15.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.250000]
    sizeOverLifeXY: [0.000000, [3.000000, 3.000000], 0.900000, [2.000000, 2.000000]]
    sizeVariation: [1.000000, 1.000000]
    sprite: "../../Gfx/Particles/alpha/o2SMOKEB"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 0.215000, 0.179000, 0.178100, 0.420000, 0.000000, 0.900000, 0.000000]
    velocityVariation: 1.000000
layer3:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.169800, 0.295700, 0.990000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [0.000000, [255.000000, 235.696503, 186.614807, 255.000000], 0.987900, [255.000000, 225.910507, 187.451401, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, [0.000000, 0.000000, -0.366400], 0.200000, [0.006000, 0.006000, -10.000000], 0.330000, [0.010000, 0.010000, 0.358500], 0.900000, [0.000000, 0.000000, -0.340600]]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 6.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.200000, [2.000000, 2.000000], 0.900000, [2.000000, 2.000000]]
    sizeVariation: [0.500000, 0.500000]
    sprite: "../../Gfx/Particles/alpha/o2SMOKEB"
    startTime: 0.000000
    type: "layer"
    velocity: 6.000000
    velocityOverLife: [0.000000, 0.204400, 0.200000, 0.613100, 0.420000, 0.000000, 0.900000, 0.000000]
    velocityVariation: 1.000000
