emitter:
    emissionAngle: 360.000000
    emissionRange: 1.000000
    emissionVector: [-0.000000, 0.390000, -0.000000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.407100, 0.435600, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [175.000000, 179.000000, 178.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, [1.000000, 0.000000, 1.200000], 0.010000, [-1.000000, 0.000000, 1.200000], 0.030000, [1.000000, 0.000000, 1.200000], 0.040000, [-1.000000, 0.000000, 1.200000], 0.050000, [1.000000, 0.000000, 1.200000], 0.070000, [-1.000000, 0.000000, 1.200000], 0.080000, [1.000000, 0.000000, 1.200000], 0.090000, [-1.000000, 0.000000, 1.200000], 0.110000, [1.000000, 0.000000, 1.200000], 0.120000, [-1.000000, 0.000000, 1.200000], 0.140000, [1.000000, 0.000000, 1.200000], 0.150000, [-1.000000, 0.000000, 1.200000], 0.170000, [1.000000, 0.000000, 1.200000], 0.190000, [-1.000000, 0.000000, 1.200000]]
    forceCount: 1
    forceOverLife0: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer 0"
    number: 40.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [3.500000, 3.500000]
    spin: 10.000000
    spinVariation: 10.000000
    sprite: "../../Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityOverLife: [0.000000, 2.174600, 0.180400, 0.406700, 1.000000, 0.100000]
    velocityVariation: 12.457500
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.315500, 0.383800, 0.701000, 0.094900, 1.000000, 0.000000]
    angle: 50.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [176.000000, 179.000000, 178.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, 0.300000]
    forceCount: 1
    forceOverLife0: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 16.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Layer 1"
    number: 25.000000
    numberVariation: 50.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.000000, 2.000000]
    sprite: "../../Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 14.000000
    velocityOverLife: [0.000000, 2.149500, 0.030000, 2.290000, 0.100000, 0.090000]
    velocityVariation: 14.000000
layer2:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.001600, 0.000000, 0.300700, 0.397400, 1.000000, 0.000000]
    angle: 0.000000
    blending: 1
    colorOverLife: [176.000000, 179.000000, 179.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Part"
    number: 25.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [3.500000, 3.500000]
    spin: 10.000000
    spinVariation: 10.000000
    sprite: "../../Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 6.000000, 0.013100, 1.421900, 0.110000, 1.100000]
    velocityVariation: 7.000000
