emitter:
    emissionAngle: 0.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "dirt"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.859000, 0.682432, 0.824818, 1.000000, 0.000000]
    blending: 1
    colorOverLife: [192.431900, 158.260696, 70.894936, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -3.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 25.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "dirt"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, -0.500000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [3.500000, 3.500000]
    sizeOverLifeXY: [0.000000, [3.000000, 3.000000], 1.000000, [4.000000, 4.000000]]
    sprite: "../../../Gfx/Particles/alpha/Dirt_exp_white"
    startTime: 0.000000
    type: "layer"
    velocity: 10.000000
    velocityOverLife: [0.000000, 0.300000, 0.310500, 0.136600]
