emitter:
    emissionAngle: 1.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, -0.000000, 0.500000]
    emissionVectorInverted: true
    name: "smoke"
    radius: 1.000000
    shortEffect: false
    size: [0.000000, 1.200000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.048800, 0.558900, 0.548315, 0.419379, 1.000000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    force0: [0.000000, 0.000000, 0.500000]
    force1: [0.000000, 0.700000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.800000]
    forceOverLife1: [0.000000, 0.000000, 1.000000, 1.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 10.000000
    lifeVariation: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke2"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.000000, [2.000000, 2.000000], 30.000000, [2.000000, 2.000000]]
    sizeOverLifeXY: [0.000000, [0.671533, 0.671533], 0.092135, [1.366381, 1.366381], 0.451685, [1.638489, 1.638489], 1.000000, [4.000000, 4.000000]]
    sizeVariation: [1.000000, 1.000000]
    spinVariation: -10.000000
    sprite: "../../../Gfx/Particles/alpha/thick_smoke"
    startTime: 0.000000
    type: "layer"
    velocity: [0.000000, 0.600000, 7.000000, 0.600000]
    velocityVariation: [0.000000, 0.400000, 7.000000, 0.400000]
