emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [1.000000, -0.500000, 0.000000]
    emissionVectorInverted: true
    name: "snow_top"
    radius: 700.000000
    shortEffect: false
    size: [300.000000, 0.000000, 1.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.100000, 0.300000, 1.000000, 0.000000]
    colorOverLife: [228.548630, 242.108948, 247.918289, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "snow_top1"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.003000
    size: [100.000000, 100.000000]
    spin: 20.000000
    spinVariation: 20.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog_white"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 40.000000
    velocityVariation: 60.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.100000, 0.100000, 0.927711, 0.100584, 1.000000, 0.000000]
    colorOverLife: [228.548630, 242.108948, 247.918289, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "snow_top"
    number: 150.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 10.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.003000
    size: [3.000000, 3.000000]
    spin: 100.000000
    spinVariation: 100.000000
    sprite: "../../../../../../Gfx/Particles/UI/o2_expGlowB"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 40.000000
    velocityVariation: 60.000000
