emitter:
    emissionRange: 0.000000
    emissionVector: [0.010000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "6_glow_tank"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 1.000000, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 200.595322, 142.439682, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 30.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 0.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow_tank"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [240.000000, 273.000000]
    sprite: "../../../../../Gfx/Particles/UI/Shop/type59_giftshop/glow"
    startTime: 0.000000
    type: "layer"
