emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [-0.000000, 1.000000, 0.010000]
    emissionVectorInverted: true
    name: "smoke_s"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.271500, 0.380200, 0.580100, 0.390900, 0.876300, 0.022100, 1.000000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [202.000000, 214.000000, 218.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1.500000
    force0: [0.000000, 1.000000, 2.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 1.000000, 2.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.500000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke_s"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [1.500000, 1.500000]
    sizeOverLifeXY: [0.000000, [0.200000, 0.200000], 1.000000, [1.000000, 1.000000]]
    spin: -90.000000
    spinOverLife: [0.000400, 1.000000, 1.000000, 0.000000]
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.100000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 1.000000, 0.000000]
