emitter:
    emissionAngle: 0.0000
    emissionRange: 0.0000
    emissionVector: [0.0000, 0.0000, 1.0000]
    emissionVectorInverted: "true"
    name: "flash_top"
    shortEffect: "true"
    size: [0.0000, 0.0000, 0.0000]
    type: "point"

layer0:
    activeLODS: [1, 1, 1, 0]
    alphaOverLife: 0.5000
    angle: 90.0000
    angleVariation: 90.0000
    deltaTime: 0.0000
    deltaVariation: 0.0000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: "false"
    enableFrameBlend: "false"
    endTime: 0.0500
    frameOverLifeEnabled: "false"
    frameOverLifeFPS: 0.0000
    inheritPosition: "true"
    isLong: "false"
    isLooped: "false"
    layerType: "single"
    life: 0.0500
    loopEndTime: 2.0000
    loopSpriteAnimation: "true"
    loopVariation: 0.0000
    name: "flash_top"
    particleOrientation: 4
    pivotPoint: [0.0000, 0.0000]
    randomFrameOnStart: "false"
    randomSpinDirection: "false"
    scaleVelocityBase: 0.0000
    scaleVelocityFactor: 0.0000
    size: [3.0000, 1.0000]
    sprite: "../../../Gfx/Particles/gun_small_front"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.0000
    type: "layer"
    velocity: 1.0000

