emitter:
    emissionAngle: 0.000000
    emissionRange: 120.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "bamboocanopy01"
    shortEffect: false
    size: [3.000000, 5.000000, 5.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [145.210114, 118.805450, 76.564201, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris2"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.050000, 1.000000]
    sizeVariation: [0.030000, 0.100000]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
layer1:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.152300, 0.325600, 0.605300, 0.233900, 0.736000, 0.161200, 1.000000, 0.000000]
    blending: 1
    colorOverLife: [182.000000, 147.000000, 102.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 5.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 400.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.500000, 2.500000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [2.000000, 2.000000]]
    sprite: "../../../Gfx/Particles/alpha/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 0.200000
    velocityVariation: 0.200000
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [145.000000, 119.000000, 76.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.030000, 0.500000]
    sizeVariation: [0.100000, 0.100000]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [145.000000, 119.000000, 76.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris3"
    number: 500.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.010000, 0.200000]
    sizeVariation: [0.100000, 0.200000]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
