emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "lod"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 0, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.050000, 1.000000, 0.633600, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [122.000000, 109.000000, 77.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, [0.000000, 0.000000, -2.000000], 0.900000, [0.000000, 0.000000, -0.938700]]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 1.000000, 7.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 6.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "LoD"
    number: 5.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.500000, 1.500000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.356100, [2.802300, 2.802300], 0.900000, [4.240400, 4.240400]]
    sizeVariation: [0.500000, 0.500000]
    spin: 30.000000
    spinOverLife: 1.000000
    spinVariation: 5.082200
    sprite: "../../../Gfx/Particles/alpha/o2SMOKEB_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.052500, 0.587800, 0.434800, 0.450000, 0.906400, 0.497700]
    velocityVariation: 1.000000
