emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "glow"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.260038, 0.756553, 0.541109, 0.422108, 0.813333, 0.134424, 0.993562, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 103.595329, 27.891050, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 0.500000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [10.000000, 10.000000]
    sprite: "../../../Gfx/Particles/alpha/o2_expGlowB"
    startTime: 0.000000
    type: "layer"
layer1:
    activeLODS: [0, 0, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.307839, 0.256638, 0.690249, 0.044886, 0.993562, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 103.595329, 27.891050, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 0.500000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glowlod"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [10.000000, 10.000000]
    sprite: "../../../Gfx/Particles/alpha/o2_expGlowB"
    startTime: 0.000000
    type: "layer"
