emitter:
    emissionAngle: 0.000000
    emissionRange: 120.000000
    emissionVector: [-0.800000, -1.000000, -1.000000]
    emissionVectorInverted: true
    name: "smoke"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.302100, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [103.000000, 105.000000, 107.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 16.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smok"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [40.000000, 40.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.108800, [2.515300, 2.515300], 1.000000, [6.000000, 6.000000]]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 300.000000
    velocityOverLife: [0.000000, 1.000000, 0.157900, 0.211700, 0.996500, 0.000000]
    velocityVariation: 300.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.198900, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [186.000000, 191.000000, 193.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 16.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke1"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [40.000000, 40.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.108800, [2.515300, 2.515300], 1.000000, [6.000000, 6.000000]]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 300.000000
    velocityOverLife: [0.000000, 1.000000, 0.157900, 0.211700, 0.996500, 0.000000]
    velocityVariation: 300.000000
