emitter:
    emissionAngle: 0.000000
    emissionRange: 120.000000
    emissionVector: [0.200000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "fire_debris2"
    shortEffect: false
    size: [25.000000, 0.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.226600, 0.256500, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [0.000000, [255.000000, 75.000000, 39.000000, 255.000000], 0.992600, [255.000000, 196.000000, 148.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.030000
    size: [2.000000, 2.000000]
    sprite: "../../../../Gfx/Particles/UI/Iskr"
    startTime: 0.000000
    type: "layer"
    velocity: 60.000000
    velocityVariation: 30.000000
