emitter:
    emissionAngle: 1.000000
    emissionRange: 10.000000
    emissionVector: [0.200000, -0.300000, 0.000000]
    emissionVectorInverted: true
    name: "house_smoke"
    radius: 1.000000
    shortEffect: false
    size: [0.000000, 1.200000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.078300, 0.000000, 0.153100, 0.339400, 0.491100, 0.091700, 0.980000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [0.001500, [59.000000, 62.000000, 58.000000, 255.000000], 0.997600, [142.688705, 135.809296, 140.968903, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 10000.000000
    force0: [0.000000, 0.000000, 0.500000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.800000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 12.000000
    lifeVariation: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke1"
    number: 2.000000
    numberVariation: 3.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [25.000000, 25.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.604400, [2.441900, 2.441900], 0.990000, [6.000000, 6.000000]]
    sizeVariation: [0.000000, [2.000000, 2.000000], 7.190000, [2.000000, 2.000000]]
    spinVariation: -8.000000
    sprite: "../../../../Gfx/Particles/UI/Fx_DustSpray_two"
    startTime: 0.000000
    type: "layer"
    velocity: 15.000000
    velocityVariation: 20.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.047700, 0.143300, 1.000000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [0.004900, [0.000000, 0.000000, 0.000000, 255.000000], 0.245100, [110.560303, 110.560303, 110.560303, 255.000000], 0.434500, [70.000000, 76.000000, 75.000000, 255.000000], 0.623800, [125.280197, 125.280197, 125.280197, 255.000000], 0.762100, [69.000000, 72.000000, 73.000000, 255.000000], 0.864100, [148.626404, 148.626404, 148.626404, 255.000000], 0.997600, [142.688705, 135.809296, 140.968903, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 10000.000000
    force0: [0.000000, 0.000000, 0.500000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.800000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 9.000000
    lifeVariation: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke2"
    number: 2.000000
    numberVariation: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [25.000000, 25.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.119400, [0.697000, 0.697000], 0.460000, [1.270100, 1.270000], 1.000000, [3.845300, 5.832400]]
    sizeVariation: [0.000000, [2.000000, 2.000000], 7.520000, [2.000000, 2.000000]]
    spinVariation: -10.000000
    sprite: "../../../../Gfx/Particles/UI/R_dust_density"
    startTime: 0.000000
    type: "layer"
    velocity: 15.000000
    velocityVariation: 20.000000
