emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "exp"
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.468613, 1.000000, 0.000000]
    angle: -5.000000
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 0.100000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 20.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 0.200000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "exp"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [0.000000, -0.100000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.500000
    scaleVelocityFactor: 0.001000
    size: [15.000000, 15.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.990000, [12.000000, 12.000000]]
    sprite: "../../../../../../Gfx/Particles/UI/exp_anim_fire"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 350.000000
    velocityOverLife: [0.000000, 1.000000, 0.150000, 0.400000]
