emitter:
    emissionAngle: 0.000000
    emissionRange: 160.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "flash_top"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.300000, 0.990000, 0.000000]
    angle: 1.000000
    angleVariation: 180.000000
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 0.100000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 64.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.200000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "flash Clone"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [8.000000, 8.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.990000, [16.000000, 16.000000]]
    sprite: "../../../../../../Gfx/Particles/UI/fire"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 100.000000
    velocityVariation: 100.000000
