emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [-0.800000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "fire_tank1"
    shortEffect: false
    size: [50.000000, 0.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.218295, 1.000000, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    colorOverLife: [72.000000, 74.000000, 79.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [70.000000, 70.000000]
    sizeVariation: [20.000000, 20.000000]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 30.000000
    velocityVariation: 30.000000
