emitter:
    emissionRange: 0.000000
    emissionVector: [-1.000000, -0.200000, 0.000000]
    emissionVectorInverted: true
    name: "bag"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 4.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "bag"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [240.000000, 270.000000]
    sizeOverLifeXY: [0.000000, [0.950000, 0.950000], 0.500000, [1.000000, 1.000000], 0.990000, [0.950000, 0.950000]]
    spin: 1.000000
    spinOverLife: [0.000000, -1.000000, 1.000000, 1.000000]
    sprite: "../../../../../Gfx/Particles/UI/Shop/gold_bag"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 0.010000
