emitter:
    emissionRange: 60.000000
    emissionVector:
        externalVariable: "game_time"
        modification_line: [0.000000, [1.000000, 1.000000, 1.000000], 0.100000, [1.000000, 1.000000, 1.000000], 0.300000, [1.000000, 4.000000, 1.000000], 0.500000, [1.000000, 1.000000, 1.000000], 0.700000, [1.000000, -4.000000, 1.000000], 1.000000, [1.000000, 1.000000, 1.000000]]
        value_line: [0.000000, 0.200000, -1.000000]
    emissionVectorInverted: true
    name: "weather_effects"
    shortEffect: false
    size: [100.000000, 100.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 0, 0, 0]
    alphaOverLife: 0.500000
    angle: 0.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [255.000000, 255.000000, 255.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 10.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "snow"
    number: 150.000000
    particleOrientation: 1
    pivotPoint: [5.000000, 5.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 1.000000
    size: [0.150000, 0.150000]
    spin: 20.000000
    spinVariation: 20.000000
    sprite: "../../../Gfx/Particles/alpha/fog_white_snow"
    startTime: 0.000000
    type: "layer"
    velocity:
        externalVariable: "game_time"
        modification_line: [0.000000, 1.000000, 0.100000, 1.100000, 0.200000, 1.000000, 0.300000, 1.200000, 0.400000, 1.000000, 0.500000, 1.100000, 0.600000, 1.000000, 0.700000, 1.200000, 0.800000, 1.000000, 0.900000, 1.100000, 0.990000, 1.000000]
        value_line: 3.000000
    velocityVariation: 2.000000
