emitter:
    emissionRange: 0.000000
    emissionVector: [-1.000000, -0.200000, 0.000000]
    emissionVectorInverted: true
    name: "dust"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.120482, 0.105109, 0.802065, 0.098978, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 300.000000
    colorOverLife: [151.000000, 153.000000, 149.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 15.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [80.000000, 80.000000]
    sizeVariation: [20.000000, 20.000000]
    sprite: "../../../../../../Gfx/Particles/UI/fog"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 60.000000
    velocityVariation: 40.000000
