emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [0.000000, -0.010000, 0.010000]
    emissionVectorInverted: true
    name: "water"
    shortEffect: false
    size: [1.000000, 1.000000, 1.000000]
    type: "point"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.472200, 0.461400, 0.433600, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [98.000000, 136.000000, 183.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 10000.000000
    force0: [0.000000, 0.000000, -5.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.381600, 0.809500, 0.990000, 5.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life:
        externalVariable: "velocity"
        modification_line: [0.000000, 1.000000, 0.990000, 0.500000]
        value_line: 1.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "water1"
    number:
        externalVariable: "velocity"
        modification_line: [0.000000, 1.000000, 0.990000, 6.000000]
        value_line: 10.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [1.000000, 1.000000]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../../Gfx/Particles/alpha/water_one"
    startTime: 0.000000
    type: "layer"
    velocity: 60.000000
    velocityVariation: 200.000000
layer1:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.292200, 0.600000, 0.096800, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [98.000000, 136.000000, 183.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 10000.000000
    force0: [0.000000, 0.000000, -5.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 5.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life:
        externalVariable: "velocity"
        modification_line: [0.000000, 1.000000, 0.990000, 0.500000]
        value_line: 1.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "water2"
    number:
        externalVariable: "velocity"
        modification_line: [0.000000, 1.000000, 1.000000, 6.000000]
        value_line: 10.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [2.000000, 2.000000]]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../../Gfx/Particles/alpha/dust_water"
    startTime: 0.000000
    type: "layer"
    velocity: 60.000000
    velocityVariation: 200.000000
