emitter:
    emissionAngle: 0.000000
    emissionRange: 120.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "debris"
    shortEffect: false
    size: [2.000000, 2.000000, 3.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [191.000000, 157.000000, 104.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris"
    number: 100.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.100000, 0.100000]
    spin: 180.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_one"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 2.000000
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [189.000000, 158.000000, 111.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris2"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.300000, 0.150000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_three"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 3.000000
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [149.000000, 119.000000, 71.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 15.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris3"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.100000]
    spin: 200.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_one"
    startTime: 0.000000
    type: "layer"
    velocity: 4.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 2.000000
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [199.000000, 164.000000, 110.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 26.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris4"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.100000]
    spin: 300.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_three"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
    velocityVariation: 3.000000
