emitter:
    emissionAngle: 1.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, -0.000000, 0.500000]
    emissionVectorInverted: true
    name: "fog"
    radius: 0.200000
    shortEffect: false
    size: [0.000000, 1.200000, 0.000000]
    type: "oncircle"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.078300, 0.000000, 0.189100, 0.505100, 0.645400, 0.492700, 0.980000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [141.019501, 145.214005, 155.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 30.000000
    force0: [0.000000, 0.000000, 0.500000]
    force1: [1.000000, 0.000000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.800000]
    forceOverLife1: [0.000000, 0.000000, 0.323100, 0.042700, 0.489000, 0.131500, 0.581500, 0.347600, 0.699000, 0.590300, 0.800300, 0.779700, 0.888400, 0.930700, 0.960400, 1.031300, 1.000000, 1.055000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 3.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke1"
    number: 4.000000
    numberVariation: 3.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.990000, [4.000000, 4.000000]]
    sizeVariation: [2.000000, 2.000000]
    spinVariation: -8.000000
    sprite: "../../../Gfx/Particles/alpha/Fx_DustSpray_two"
    startTime: 0.000000
    type: "layer"
    velocity: 0.800000
    velocityVariation: 0.400000
