emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [-1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "flag"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    blending: 1
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: true
    endTime: 1.000000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 16.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 1000.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "flag"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [25.000000, 25.000000]
    sprite: "../../../../Gfx/Particles/flag/flag"
    startTime: 0.000000
    type: "layer"
