emitter:
    emissionAngle: 0.000000
    emissionRange: 20.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "dust"
    shortEffect: false
    size: [1.000000, 3.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.068500, 0.468300, 0.583900, 0.254700, 1.000000, 0.000000]
    blending: 1
    colorOverLife: [117.000000, 120.000000, 125.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.060000
    force0: [0.000000, 0.000000, -10.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 25.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "dust"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 3.000000], 1.000000, [4.000000, 4.000000]]
    sprite: "../../../Gfx/Particles/alpha/fog"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.147400, 0.094900, 0.996600, 0.055500]
    velocityVariation: 8.000000
