emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.010000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.090000, 1.000000, 0.930000, 1.000000, 1.000000, 0.000000]
    blending: 1
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 36.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "air"
    particleOrientation: 8
    pivotPoint: [0.000000, -0.300000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 1.000000
    size: [6.000000, 10.000000]
    sizeOverLifeXY: [0.000000, [1.300000, 1.300000], 1.000000, [0.300000, 0.300000]]
    sprite: "../../../Gfx/Particles/01_tutorial_tut/air"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.126000, 0.683900, 0.038400, 1.000000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [201.000000, 210.000000, 225.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 30.000000
    force0: [0.000000, 0.000000, 0.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.200000, 0.200000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [4.000000, 4.000000]]
    sizeVariation: [2.000000, 2.000000]
    sprite: "../../../Gfx/Particles/alpha/fog"
    startTime: 1.000000
    type: "layer"
