emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [1.000000, 0.000000, 0.100000]
    emissionVectorInverted: true
    name: "air2"
    radius: 100.000000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1.000000
    force0: [10.000000, -9.000000, 0.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.300000, 0.000000, 0.310000, 1.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    innerEmitterPath: "air2.1.yaml"
    isLong: false
    isLooped: false
    layerType: "superEmitter"
    life: 60.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "air"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    startTime: 0.000000
    type: "layer"
    velocity: 30.000000
