emitter:
    emissionRange: 20.000000
    emissionVector: [0.000000, -1.000000, 1.000000]
    emissionVectorInverted: true
    name: "smoke"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.040000, 0.150000, 0.809764, 0.067386, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 300.000000
    colorOverLife: [204.000000, 195.000000, 228.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [80.000000, 80.000000]
    sizeOverLifeXY: [0.000000, [0.100000, 0.100000], 1.000000, [1.000000, 1.000000]]
    sizeVariation: [20.000000, 20.000000]
    spin: 30.000000
    spinVariation: 10.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog_white"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 30.000000
    velocityVariation: 20.000000
