emitter:
    emissionAngle: 1.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, -0.000000, 0.500000]
    emissionVectorInverted: true
    name: "fog"
    radius: 1.000000
    shortEffect: false
    size: [2.000000, 1.000000, 0.000000]
    type: "rect"
