emitter:
    emissionAngle: 0.000000
    emissionRange: 90.000000
    emissionVector: [0.000000, 0.000000, 0.010000]
    emissionVectorInverted: true
    name: "firefly"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.200000, 4.000000]
    type: "oncircle"
layer0:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.200378, 0.852555, 0.440000, 1.000000, 0.712665, 0.791241, 0.997500, 0.000000]
    blending: 1
    colorOverLife: [253.175095, 255.000000, 200.214005, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.050000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 30.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 15.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "firefly"
    number: 110.000000
    particleOrientation: 1
    pivotPoint: [5.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.350000, 0.350000]
    sizeVariation: [0.090000, 0.090000]
    spin: 70.000000
    spinVariation: [0.000000, 70.000000, 0.020000, 100.000000, 0.050000, 60.000000]
    sprite: "../../../Gfx/Particles/22_italy_it_night/firefly"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
