emitter:
    emissionAngle: 0.000000
    emissionRange: 10.000000
    emissionVector: [-1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "burned_paper"
    shortEffect: false
    size: [0.000000, 200.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.200000, 1.000000, 0.910000, 1.000000, 1.000000, 0.000000]
    colorOverLife: [214.859924, 175.385208, 145.198441, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    force0: [-10.000000, 0.000000, 0.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 13.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "burned_paper"
    numberVariation: 1.000000
    particleOrientation: 1
    pivotPoint: [10.000000, 10.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.008000
    size: [4.000000, 2.000000]
    sizeVariation: [2.000000, 2.000000]
    spin: 100.000000
    spinVariation: 30.000000
    sprite: "../../../../../Gfx/Particles/UI/burned_paper"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 60.000000
    velocityVariation: 60.000000
