emitter:
    emissionAngle: 0.000000
    emissionRange: 120.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "barrak01"
    shortEffect: false
    size: [5.000000, 3.000000, 2.600000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [149.000000, 131.000000, 140.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris2"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.050000, 1.000000]
    sizeVariation: [0.250000, 0.100000]
    spin: 90.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
layer1:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.147228, 0.370235, 0.604207, 0.374892, 0.735400, 0.219800, 1.000000, 0.000000]
    blending: 1
    colorOverLife: [182.000000, 147.000000, 102.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 5.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 400.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.500000, 2.500000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [2.000000, 2.000000]]
    sprite: "../../../Gfx/Particles/alpha/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 0.200000
    velocityVariation: 0.200000
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [144.000000, 177.000000, 153.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.030000, 0.500000]
    sizeVariation: [0.100000, 0.100000]
    spin: 120.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorRandom: [0.000000, [255.000000, 255.000000, 255.000000, 255.000000], 0.998800, [143.000000, 198.000000, 151.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -8.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris3"
    number: 500.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.010000, 0.200000]
    sizeVariation: [0.100000, 0.200000]
    spin: 120.000000
    spinVariation: 90.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 5.000000
    velocityVariation: 2.000000
