emitter:
    emissionRange: 0.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "glow"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.160612, 0.000000, 0.470000, 0.400000, 0.824092, 0.000000, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 227.373535, 47.813229, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 100.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow1"
    numberVariation: 2.000000
    particleOrientation: 8
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [4.000000, 2.000000]
    sprite: "../../../Gfx/Particles/alpha/glow_anim_low"
    startTime: 0.000000
    type: "layer"
