emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [0.000000, 0.000000, 0.500000]
    emissionVectorInverted: true
    name: "debris"
    shortEffect: false
    size: [3.000000, 0.000000, 1.800000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [198.000000, 159.000000, 96.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.750000, 0.100000]
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders"
    startTime: 0.000000
    type: "layer"
    velocity: 0.010000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [189.000000, 115.000000, 51.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood2"
    number: 60.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.050000]
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 0.100000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [173.000000, 152.000000, 117.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.310000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 15.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood3"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.100000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [195.000000, 149.000000, 84.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 26.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris_wood4"
    number: 60.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.050000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/flinders_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
