emitter:
    emissionRange: 120.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "hay"
    shortEffect: false
    size: [5.000000, 4.000000, 3.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [152.291824, 148.692596, 134.303497, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -40.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "hay"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.500000]
    sizeVariation: [1.000000, 1.000000]
    spin: 5.000000
    spinVariation: 5.000000
    sprite: "../../../Gfx/Particles/alpha/hay"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.035500, 0.113100]
    velocityVariation: 3.000000
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [154.000000, 128.000000, 93.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -40.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "hay1"
    number: 300.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.800000, 0.800000]
    sizeVariation: [1.000000, 1.000000]
    spin: 10.000000
    spinVariation: 10.000000
    sprite: "../../../Gfx/Particles/alpha/hay"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.020000, 0.100000]
    velocityVariation: 3.000000
