emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, -1.000000]
    emissionVectorInverted: true
    name: "lightning"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: 0.700000
    blending: 3
    colorOverLife: [194.000000, 255.000000, 245.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 0.200000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "lightning"
    number: 100.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.900000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [20.000000, 30.000000]
    sprite: "../../../Gfx/Particles/18_canal_cn/lightning"
    startTime: 0.000000
    type: "layer"
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.300000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [194.000000, 255.000000, 245.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 0.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "lightning1"
    number: 100.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.900000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [40.000000, 40.000000]
    sprite: "../../../Gfx/Particles/alpha/blursnow"
    startTime: 0.000000
    type: "layer"
