emitter:
    emissionAngle: 0.000000
    emissionRange: 90.000000
    emissionVector: [0.000000, 0.000000, 0.500000]
    emissionVectorInverted: true
    name: "fire_debris"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 1.000000, 1.000000, 0.000000]
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, 0.000000, -10.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.400000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 6.000000
    inheritPosition: false
    innerEmitterPath: "explosion_AMX_Dracula_7_fire_debris_iner.yaml"
    isLong: false
    isLooped: false
    layerType: "superEmitter"
    life: 20.000000
    loopEndTime: 10.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "fire_debris_spawn"
    number: 40.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [0.250000, 0.250000]
    sizeVariation: [0.500000, 0.500000]
    sprite: "../../"
    startTime: 0.000000
    type: "layer"
    velocity: 15.000000
    velocityOverLife: [0.000000, 1.000000, 1.000000, 0.300000]
    velocityVariation: 15.000000
