emitter:
    emissionAngle: 0.000000
    emissionRange: 100.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "sparks"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: 0.100000
    blending: 2
    colorOverLife: [0.000000, [255.000000, 23.906614, 15.937743, 255.000000], 0.996416, [247.918289, 188.214005, 115.245132, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 10000.000000
    force0: [0.000000, 0.000000, -4.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.500000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.010000
    scaleVelocityFactor: 1.000000
    size: [0.050000, 0.050000]
    sizeOverLifeXY: [0.000000, [1.500000, 1.500000], 0.990000, [0.000000, 0.000000]]
    sizeVariation: [0.030000, 0.040000]
    sprite: "../../../Gfx/Particles/alpha/o2_expGlowB"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityVariation: 5.000000
