emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "snow"
    shortEffect: false
    size: [0.000000, 50.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.200000, 0.150000, 1.000000, 0.000000]
    angle: 20.000000
    angleVariation: 200.000000
    colorOverLife: [186.268478, 202.887161, 233.750977, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 1.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "snow"
    number: 5.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.005000
    size: [70.000000, 70.000000]
    spin: 10.000000
    spinVariation: 10.000000
    sprite: "../../../../../../Gfx/Particles/UI/fog_white"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
    velocity: 15.000000
    velocityVariation: 10.000000
