emitter:
    emissionAngle: 1.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, -0.000000, 0.500000]
    emissionVectorInverted: true
    name: "fog"
    radius: 1.000000
    shortEffect: false
    size: [1.000000, 2.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 1.000000, 0.692600, 0.699300, 0.980000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [0.001500, [59.000000, 62.000000, 58.000000, 255.000000], 0.239600, [147.000000, 147.000000, 147.000000, 255.000000], 0.434500, [61.000000, 65.000000, 63.000000, 255.000000], 0.623800, [125.000000, 125.000000, 125.000000, 255.000000], 0.762100, [68.000000, 73.000000, 70.000000, 255.000000], 0.864100, [203.046707, 203.046707, 203.046707, 255.000000], 0.997600, [142.688705, 135.809296, 140.968903, 255.000000]]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    force0: [0.000000, 0.000000, 0.500000]
    force1: [0.000000, 1.000000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.800000]
    forceOverLife1: [0.000000, 0.000000, 0.990000, 1.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke1"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.000000, [3.000000, 3.000000], 30.000000, [3.000000, 3.000000]]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.990000, [2.000000, 2.000000]]
    sizeVariation: [2.000000, 2.000000]
    spinVariation: -8.000000
    sprite: "../../../Gfx/Particles/alpha/Fx_DustSpray_two"
    startTime: 0.000000
    type: "layer"
    velocity: [0.000000, 0.800000, 7.000000, 0.800000]
    velocityVariation: [0.000000, 0.400000, 7.000000, 0.400000]
layer1:
    activeLODS: [0, 1, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.048800, 0.558900, 1.000000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [116.540855, 120.381325, 127.501945, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    force0: [0.000000, 0.000000, 0.500000]
    force1: [0.000000, 1.000000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.800000]
    forceOverLife1: [0.000000, 0.000000, 1.000000, 1.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    lifeVariation: 2.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke2"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.000000, [2.000000, 2.000000], 30.000000, [2.000000, 2.000000]]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.119400, [0.697000, 0.697000], 0.460000, [1.270100, 1.270000], 1.000000, [4.000000, 4.000000]]
    sizeVariation: [1.000000, 1.000000]
    spinVariation: -10.000000
    sprite: "../../../Gfx/Particles/alpha/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: [0.000000, 0.600000, 7.000000, 0.600000]
    velocityVariation: [0.000000, 0.400000, 7.000000, 0.400000]
layer2:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.047100, 0.105100, 0.097600, 0.223000, 0.283146, 0.250321, 0.528090, 0.182194, 0.797753, 0.078543, 1.000000, 0.000000]
    angleVariation: 120.000000
    blending: 1
    colorOverLife: [0.000000, [90.303497, 90.338501, 82.062302, 255.000000], 0.997600, [170.299606, 170.268494, 152.805405, 255.000000]]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: true
    endTime: 1000.000000
    force0: [0.000000, 0.000000, 0.500000]
    force1: [0.000000, 1.000000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.800000]
    forceOverLife1: [0.000000, 0.000000, 1.000000, 1.000000]
    frameOverLifeEnabled: true
    frameOverLifeFPS: 6.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    lifeVariation: [0.000000, 2.000000, 30.000000, 2.000000, 120.000000, 2.000000]
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke3"
    number: [0.000000, 5.000000, 44.607800, 5.000000, 400.000000, 5.000000]
    numberVariation: [0.000000, 5.000000, 84.175102, 5.000000]
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.000000, 2.000000]
    sizeOverLifeXY: [0.000000, [0.483200, 0.483200], 0.179700, [0.636600, 0.636600], 1.000000, [1.297900, 1.297900]]
    sizeVariation: [1.000000, 1.000000]
    sprite: "../../../Gfx/Particles/alpha/dum_anim"
    startTime: 0.000000
    type: "layer"
    velocity: 1.067200
    velocityOverLife: [0.000000, 1.000000, 0.530500, 0.801500, 1.000000, 0.607300, 26.790001, 0.000000, 99.469498, 0.024500]
    velocityVariation: 0.010000
