emitter:
    emissionAngle: 60.000000
    emissionRange: 180.000000
    emissionVector: [0.100000, -0.010000, 2.000000]
    emissionVectorInverted: true
    name: "dust_shok"
    radius: 0.300000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.037700, 0.290600, 0.559900, 0.170500, 0.990000, 0.000000]
    angle: 180.000000
    angleVariation: 180.000000
    blending: 1
    colorOverLife: [163.000000, 131.000000, 79.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 16.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    lifeVariation: 1.000000
    loopEndTime: 8.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust_shok"
    number: 100.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.401800, [3.116800, 3.116800], 1.000000, [6.000000, 6.000000]]
    sizeVariation: [0.250000, 0.250000]
    spin: 20.000000
    spinVariation: 10.000000
    sprite: "../../../Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 3.000000, 0.052500, 0.587800, 0.434800, 0.450000, 0.906400, 0.497700]
    velocityVariation: 1.000000
