emitter:
    emissionAngle: 0.000000
    emissionRange: 70.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "debris"
    shortEffect: false
    size: [3.000000, 5.000000, 3.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [132.000000, 131.000000, 97.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 16.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris_car"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.200000, 0.100000]
    sizeVariation: [0.179300, 0.080800]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_one"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 100.000000
    angleVariation: 100.000000
    blending: 1
    colorOverLife: [116.000000, 115.000000, 85.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, 0.000000, -1.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 0.990000, 30.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "debris_car2"
    number: 40.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.200000, 0.200000]
    sizeVariation: [0.050000, 0.050000]
    spin: 60.000000
    spinVariation: 60.000000
    sprite: "../../../Gfx/Particles/alpha/fragment_car_three"
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.480000, 0.300000, 0.990000, 1.003400]
