emitter:
    emissionRange: 120.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "electricity"
    shortEffect: false
    size: [0.000000, 1.300000, 1.500000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    blending: 2
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.100000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 15.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 0.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "electricity"
    number: 150.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.300000, 0.100000]
    sprite: "../../../Gfx/Particles/alpha/electricity4"
    startTime: 0.000000
    type: "layer"
