emitter:
    emissionAngle: 0.000000
    emissionRange: 360.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "water_top1"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.300000, 0.530100, 0.166900, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 3
    colorOverLife: [151.000000, 184.000000, 168.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "water2"
    number: 30.000000
    particleOrientation: 8
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [3.000000, 3.000000]]
    sprite: "../../../Gfx/Particles/alpha/water_one"
    startTime: 0.000000
    type: "layer"
    velocity: 0.200000
    velocityVariation: 0.100000
layer1:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 1.000000, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [151.000000, 184.000000, 168.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "water1"
    number: 30.000000
    particleOrientation: 8
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [3.000000, 3.000000]]
    sprite: "../../../Gfx/Particles/alpha/water"
    startTime: 0.000000
    type: "layer"
    velocity: 0.200000
    velocityVariation: 0.100000
