emitter:
    emissionRange: 20.000000
    emissionVector: [1.000000, 0.300000, 0.000000]
    emissionVectorInverted: true
    name: "dust"
    shortEffect: false
    size: [0.000000, 120.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.169847, 0.374978, 0.459048, 0.113082, 0.786260, 0.396328, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 300.000000
    blending: 1
    colorOverLife: [108.404671, 100.159531, 77.490273, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 15.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.030000
    size: [80.000000, 80.000000]
    sizeVariation: [20.000000, 20.000000]
    sprite: "../../../../../../Gfx/Particles/UI/fog"
    startTime: 0.000000
    type: "layer"
    velocity: 70.000000
    velocityVariation: 40.000000
