emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [1.000000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "sparks"
    radius: 700.000000
    shortEffect: false
    size: [0.000000, 300.000000, 1.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.100000, 0.600000, 0.836700, 0.100000, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 82.245102, 13.945500, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks1"
    number: 2.000000
    numberVariation: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.008000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [5.305300, 5.305300], 0.505100, [6.407100, 6.407100], 1.000000, [4.364100, 4.364100]]
    sizeVariation: [0.500000, 0.500000]
    sprite: "../../../../../../Gfx/Particles/UI/Blur_sparks"
    startTime: 0.000000
    type: "layer"
    velocity: 150.000000
    velocityVariation: 15.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.100000, 0.800000, 0.836700, 0.100000, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 82.245102, 13.945500, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks2"
    number: 2.000000
    numberVariation: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.012000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [5.305300, 5.305300], 0.505100, [6.407100, 6.407100], 1.000000, [4.364100, 4.364100]]
    sizeVariation: [0.500000, 0.500000]
    sprite: "../../../../../../Gfx/Particles/UI/Blur"
    startTime: 0.000000
    type: "layer"
    velocity: 100.000000
    velocityVariation: 15.000000
layer2:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.100000, 0.700000, 0.841800, 0.263400, 1.000000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 82.245102, 13.945500, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.300000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks3"
    numberVariation: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.016000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [5.305300, 5.305300], 0.505100, [6.407100, 6.407100], 1.000000, [4.364100, 4.364100]]
    sizeVariation: [0.500000, 0.500000]
    sprite: "../../../../../../Gfx/Particles/UI/Blur_sparks"
    startTime: 0.000000
    type: "layer"
    velocity: 150.000000
    velocityVariation: 15.000000
