emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "battle_bottom"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.139200, 0.970800, 0.480000, 1.000000, 0.856900, 0.970800, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 103.000000, 53.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 100.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "battle_bottom"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [90.000000, 5.000000]
    sizeOverLifeXY: [0.000000, [0.500000, 1.000000], 0.470000, [3.000000, 1.000000], 1.000000, [0.500000, 1.000000]]
    sprite: "../../../Gfx/Particles/alpha/blursnow"
    startTime: 0.000000
    type: "layer"
