emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "battle_glow1"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.450000, 0.500000, 1.000000, 0.000000]
    angle: 90.000000
    blending: 3
    colorOverLife: [255.000000, 119.000000, 74.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: true
    endTime: 100.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 16.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "battle_glow"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [150.000000, 190.000000]
    sprite: "../../../Gfx/Particles/alpha/blursnow"
    startTime: 0.000000
    type: "layer"
