emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [0.000000, 0.000000, 0.010000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.430000, 0.130000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 45.000000, 26.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 2.000000
    deltaVariation: 2.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: true
    layerType: "particles"
    life: 0.500000
    lifeVariation: 0.500000
    loopEndTime: 1000.000000
    loopSpriteAnimation: true
    loopVariation: 2.000000
    name: "Layer1"
    number: 6.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [800.000000, 300.000000]
    sprite: "../../../Gfx/Particles/alpha/dust_water"
    startTime: 0.000000
    type: "layer"
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.425400, 0.078000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 45.000000, 26.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 2.000000
    deltaVariation: 2.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: true
    layerType: "particles"
    life: 0.500000
    lifeVariation: 0.500000
    loopEndTime: 1000.000000
    loopSpriteAnimation: true
    loopVariation: 2.000000
    name: "Layer1 Clone"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [800.000000, 300.000000]
    sprite: "../../../Gfx/Particles/alpha/o2_expGlow"
    startTime: 0.000000
    type: "layer"
