emitter:
    emissionAngle: 0.000000
    emissionRange: 50.000000
    emissionVector: [0.200000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "sparks_right3"
    shortEffect: false
    size: [100.000000, 0.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.152381, 0.506060, 1.000000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 3
    colorRandom: [0.000000, [92.000000, 134.000000, 162.000000, 255.000000], 0.994643, [8.000000, 23.000000, 164.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.200000
    deltaVariation: 1.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1.000000
    force0: [0.000000, 300.000000, 0.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: true
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.100000
    name: "sparks"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [8.000000, -8.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.004000
    size: [3.000000, 3.000000]
    sizeOverLifeXY: [0.000000, [1.300000, 1.300000], 1.000000, [0.800000, 0.800000]]
    sizeVariation: [2.000000, 3.000000]
    spin: 200.000000
    spinVariation: 200.000000
    sprite: "../../../../Gfx/Particles/UI/Tournaments/sparks"
    startTime: 0.000000
    type: "layer"
    velocity: 400.000000
    velocityVariation: 300.000000
