emitter:
    emissionRange: 1.000000
    emissionVector: [1.000000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "sparks_right4"
    shortEffect: false
    size: [0.000000, 300.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 1.000000, 0.680000, 1.000000, 0.990000, 0.000000]
    blending: 3
    colorRandom: [0.000000, [8.000000, 23.000000, 164.000000, 255.000000], 0.992857, [92.000000, 134.000000, 162.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.200000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "sparks"
    number: 5.000000
    particleOrientation: 1
    pivotPoint: [6.000000, -6.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.006000
    size: [6.000000, 6.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.718095, [1.000000, 1.000000], 0.990000, [0.800000, 0.800000]]
    sizeVariation: [0.000000, 7.000000]
    sprite: "../../../../Gfx/Particles/UI/Tournaments/sparks"
    startTime: 0.000000
    type: "layer"
    velocity: 100.000000
    velocityVariation: 100.000000
