emitter:
    emissionAngle: 0.000000
    emissionRange: 30.000000
    emissionVector: [0.500000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "sparks_\nleft2"
    shortEffect: false
    size: [100.000000, 0.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.147727, 1.000000, 0.175238, 0.000000, 0.217143, 1.000000, 0.295238, 0.000000, 0.327619, 1.000000, 0.380952, 0.000000, 0.392381, 0.985402, 0.481905, 0.000000, 0.506667, 0.956204, 0.537143, 0.000000, 0.596190, 1.000000, 0.615238, 0.021898, 0.645714, 1.000000, 0.683810, 0.000000, 0.733333, 1.000000, 0.775238, 0.000000, 1.000000, 0.000000]
    blending: 3
    colorRandom: [0.000000, [255.000000, 0.996109, 0.996109, 255.000000], 0.996429, [255.000000, 107.945526, 49.805447, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 10.000000
    particleOrientation: 1
    pivotPoint: [6.000000, -6.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.004000
    size: [3.000000, 3.000000]
    sizeVariation: [2.000000, 3.000000]
    spin: 150.000000
    spinVariation: 150.000000
    sprite: "../../../../Gfx/Particles/UI/Tournaments/treil"
    startTime: 0.000000
    type: "layer"
    velocity: 300.000000
    velocityVariation: 300.000000
