emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "glow"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.500000, 0.990000, 0.000000]
    colorOverLife: [255.000000, 0.996109, 0.996109, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow1"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [250.000000, 250.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 1.000000, [2.000000, 2.000000]]
    spin: -20.000000
    sprite: "../../../../../Gfx/Particles/UI/glow3"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    colorOverLife: [255.000000, 0.996109, 0.996109, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow1 Clone"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [300.000000, 300.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 1.000000, [2.000000, 2.000000]]
    spin: -15.000000
    sprite: "../../../../../Gfx/Particles/UI/glow_anim_min"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.000000
    type: "layer"
