emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.010000, 0.000000]
    emissionVectorInverted: true
    name: "Particle Emitter"
    radius: 0.200000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: 0.220000
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 6.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 10.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 100.000000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow1"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [3.000000, 3.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.460000, [2.000000, 2.000000], 1.000000, [1.000000, 1.000000]]
    spin: 2.000000
    sprite: "../../../Gfx/Particles/hangar/glow_anim"
    startTime: 0.000000
    type: "layer"
    velocity: 0.010000
