emitter:
    emissionAngle: 60.000000
    emissionRange: 50.000000
    emissionVector: [0.100000, -0.010000, 1.000000]
    emissionVectorInverted: true
    name: "dust"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.000000, 2.000000]
    type: "rect"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.084130, 0.524003, 0.774379, 0.212348, 0.990000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [124.000000, 122.513618, 79.435791, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.300000
    force0: [0.000000, [0.000000, 0.000000, -2.000000], 0.300000, [0.010000, 0.000000, 0.000000], 0.900000, [0.000000, 0.000000, -0.938700]]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 8.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust"
    number: 40.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.900000, [2.000000, 2.000000]]
    sizeVariation: [0.500000, 0.500000]
    spin: [0.000000, 5.000000, 0.300000, 0.000000]
    spinOverLife: [0.000000, 1.000000, 0.300000, 0.000000]
    sprite: "../../../Gfx/Particles/alpha/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 4.000000, 0.052500, 0.587800, 0.420000, 0.100000, 0.896300, 0.131400]
    velocityVariation: 1.000000
